### PR TITLE
This fixes #17. Null and empty reference excepton for keyword and des…

### LINKED ISSUE #17: NullRef Exception from empty description
When the news description is empty, NullReferenceException from WordFinder is thrown.

### PR DESCRIPTION
**Pull request by taniameshcher**
…cription in WordFinder fixed.

### CODE REVIEW

File: WebApplication1/Model/WordFinder.cs [hunk 1]
```diff
@@ -24,10 +24,14 @@ public WordFinder(string[] separatingChars)
         public int Find(string keyword, string description)
         {
             int count = 0;
+            if (string.IsNullOrWhiteSpace(description))
+                return count;
+            if (string.IsNullOrWhiteSpace(keyword))
+            {
+                throw new Exception("There is no keyword to search");
```
Comment (alparamonov) [inline WebApplication1/Model/WordFinder.cs:31]: Thrown exception should be handled properly on higher levels later

**Review by alparamonov — APPROVED** [review]
